amap:
  api:
    snowflake:
      data-center-id: 1
      machine-id: 2
    key: <你申请的高德地图 JS版本 API-Key>
    secret: <你申请的高德地图 JS版本 API-Secret>

spring:
  thymeleaf:
    cache: false
    encoding: UTF-8

server:
  port: 1111
